---
title: "`r unique(data_full[!is.na(data_full$Fac_new), 'Fac_new'])`"
author: "Pepijn Vink"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
# Load necessary packages
library(dplyr) # for data manipulation
library(ggplot2) # for visualization
library(magrittr) # for the pipe operator
library(tibble) # to create tibbles
library(foreign) # to import spss files
library(purrr) # for functional programming
library(skimr) # for descriptives
library(knitr)
library(rlang)

# Load necessary functions
## for descriptives
source("~/surfdrive/Shared/OS Monitor 2022/Data/Data Analysis/osm_descriptives.R")

## for attitude behavior gap
source("~/surfdrive/Shared/OS Monitor 2022/Data/Data Analysis/att_beh_gap.R")

# load variable names to use
load("~/surfdrive/Shared/OS Monitor 2022/Data/Data Analysis/variables_WP.RData")
```

```{r}
# select columns to use
data_raw <- data_full[, vars_WP]
# filter out people
dat_withoutID <- data_raw %>%
  filter(Data_consent == 1,
         pens == "niet gepensioneerd",
         wp == "wp") %>%
  mutate(missing_awareness = apply(.[,22:33], 1, function(x) x %>% is.na() %>% sum())) %>% # compute number of missings
  filter(missing_awareness <= 6) %>% # filter out persons with >6 missings
  select(-missing_awareness) # remove missingness variable

# number of eligible respondents
n_eligible <- data_raw %>%
  filter(Data_consent == 1,
         pens == "niet gepensioneerd",
         wp == "wp") %>%
  nrow()

cat("The number of eligible respondents is ", n_eligible)

# final respondents
n_final <- nrow(dat_withoutID)
cat("The final number of respondents is ", n_final)

# create ID column
ID <- 1:nrow(dat_withoutID)
dat <- cbind(ID, dat_withoutID)
```

## Get some basic descriptives

```{r}
# create descriptives for some variables
map(dat[,c("Pos_2", "OSCU", "Gen", "Nationality")], 
    table)
```

## Descriptives of Awareness {.tabset}

```{r, results='asis'}
# create list with tables
descr_aw <- dat[,23:34] %>%
  map(table)

# format tables
osm_descriptives(descr_aw, '###')
```

## Descriptives of Attitudes {.tabset}

```{r, results='asis'}
# create list with tables
descr_att <- dat[,35:46] %>%
  map(table)

# format tables
osm_descriptives(descr_att, '###')
```

## Descriptives of Behaviors {.tabset}

```{r, results='asis'}
# create list with tables
descr_beh <- dat[,47:58] %>%
  map(table) %>%
  map(as.data.frame)

# format tables
osm_descriptives(descr_beh, '###')
```

## Attitude-Behavior Gap

```{r, warning = F}
att_beh_gap_full <- att_beh_gap(data = dat)
kable(att_beh_gap_full, digits = 3)
```

## Opportunities {.tabset}

```{r}
# copy data frame to use
dat_opp <- dat %>%
  mutate_at(
    vars(dplyr::starts_with("OppMat")), as.numeric
  ) %>%
  mutate_at(
    vars(dplyr::starts_with("OppMat")),
    ~case_when(
      . == 1 | . == 2 ~ 1,
      . == 3 ~ 2,
      . == 4 | . == 5 ~ 3,
      is.na(NA) ~ NA
    )) %>%
  select(dplyr::starts_with("OppMat"))

opportunities <- dat_opp %>%
  map_df(table) %>%
  mutate(n = rowSums(.),
         missing = nrow(dat)-n)

colnames(opportunities) <- c("(Strongly) disagree", "Neutral", "(Strongly) Agree", "n", "missing")

opportunities <- as.data.frame(opportunities)

opp_rownames <- c("...improve quality of scientific knowledge",
         "...detect unethical behavior in research practices",
         "...improve diversity and inclusion in academia",
         "...improve fairness in reward and promotion systems in academia",
         "...create more career opportunities for young academics",
         "...increase the societal impact of scientific work",
         "...increase inter- or multidisciplinary collaborations between academics",
         "...improve collaborative atmosphere among collegues",
         "...improve the quality of education",
         "...learn from each others’ mistakes and talk openly about them")

rownames(opportunities) <- opp_rownames

opportunities_perc <- opportunities %>%
  mutate_at(1:3, ~ ./n*100)
```

### Raw Values

```{r}
kable(opportunities, digits = 2)
```

### Percentages

```{r}
kable(opportunities_perc, digits = 2)
```

## Barriers {.tabset}

```{r}
# copy data frame to use
dat_bar <- dat %>%
  mutate_at(
    vars(dplyr::starts_with("BarMat")), as.numeric
  ) %>%
  mutate_at(
    vars(dplyr::starts_with("BarMat")),
    ~case_when(
      . == 1 | . == 2 ~ 1,
      . == 3 ~ 2,
      . == 4 | . == 5 ~ 3,
      is.na(NA) ~ NA
    )) %>%
  select(dplyr::starts_with("BarMat"))

barriers <- dat_bar %>%
  map_df(table) %>%
  mutate(n = rowSums(.),
         missing = nrow(dat)-n)

colnames(barriers) <- c("(Strongly) disagree", "Neutral", "(Strongly) Agree", "n", "missing")

barriers <- as.data.frame(barriers)

bar_rownames <- c("...my workload is too high to integrate these practices",
                  "...I do not get time within my contract hours to do / learn this",
                  "...I do not get recognition from my supervisor for this",
                  "...it is not the norm to do this in my department (my colleagues don’t do it)",
                  "...there is insufficient practical support and training available in my department about this",
                  "...I would lose autonomy and freedom in how I do my work research",
                  "...my research does not allow for it due to for example the GDPR, embargos and or patent issues",
                  "...many OS practices do not fit with the culture of competition that exists in my department",
                  "...career promotion and success still heavily rely on “individual excellence” standards that do not fit with many OS practices",
                  "...I am afraid that if I make a mistake in my OS practices, it will be held against me (e.g., by being publicly shamed, orseen as fraudulent)")

rownames(barriers) <- bar_rownames

barriers_perc <- barriers %>%
  mutate_at(1:3, ~ ./n*100)
```

### Raw Values

```{r}
kable(barriers, digits = 2)
```

### Percentages

```{r}
kable(barriers_perc, digits = 2)
```


